# NumPy

In [3]:
import numpy as np

In [12]:
# Criando um array
a = np.array([0, 1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
1


# Criação de Arrays

In [15]:
# Construção Manual de Arrays / bidimencional
b = np.array([[0,1,2], [3,4,5]])
print(b)
# esse método me diz a dimensão desse array
print(b.ndim)
# esse método permite a visualização o formato do array. quantas linhas/colunas tem
print(b.shape)
# retorna o numero de linhas, valor da primeira dimensão
print(len(b))

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [18]:
# Criação utilizando funções
# nesta função você tem 3 parametros, inicio, até a onde e de quanto em quanto
c = np.arange(0, 100, 1)
print(c)

# é uma função que tbm permite criar um array espaçado, mas aqui você quantos elementos você quer em 
# deteerminado intervalo
d = np.linspace(1, 10, 10)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Arrays Comuns

In [22]:
# Criando um arrays de 1 (uns)
e = np.ones(10)
print(e)

# Para criar um arrays de mais de uma dimensão é preciso usar um shape, definindo linhas e colunas
f = np.ones((5,5))
print(f)

# Função zeros para arrays 0
g = np.zeros(5)
print(g)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0.]


In [29]:
# Matriz(array) de números aleatórios
h = np.random.rand(2,3)
print(h)

[[0.89412604 0.17664091 0.52236803]
 [0.0636452  0.69191811 0.13137166]]


In [25]:
# Função eye cria uma matriz de identidade e ela possui valores da sua diagonal principal (o valor é 1)
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Função diag você consegue inserir valores na sua diagonal principal - matriz bidimencional quadrada
f = np.diag(np.array([1,2,3,4]))
print(f)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Indexação e Slices de array

In [10]:
a1 = np.arange(10, 21)

print(a1)

# Fazendo um Slice no meu array - acessando posições especificas
a1[10]

# Tambem é possivel acessar as posições de forma negativa - de tras para frente 
a1[-1]

[10 11 12 13 14 15 16 17 18 19 20]


20

In [16]:
b2 = np.random.rand(5,5)

print(b2)

# Fazendo uma indexação no meu array - acessando posições especificas com arrey bidimencional
b2[0,4]

# Alterei a minha matriz/elemento para o valor 10
b2[0,1] = 10

print(b2)

[[0.16985185 0.81812412 0.95064203 0.45675537 0.59968241]
 [0.62396069 0.67522863 0.86526686 0.29417711 0.01713081]
 [0.17162772 0.69646965 0.54525772 0.88071398 0.48802663]
 [0.71067461 0.9328771  0.23747695 0.4266339  0.97153886]
 [0.38531872 0.89856086 0.91034798 0.2946781  0.38234726]]
[[ 0.16985185 10.          0.95064203  0.45675537  0.59968241]
 [ 0.62396069  0.67522863  0.86526686  0.29417711  0.01713081]
 [ 0.17162772  0.69646965  0.54525772  0.88071398  0.48802663]
 [ 0.71067461  0.9328771   0.23747695  0.4266339   0.97153886]
 [ 0.38531872  0.89856086  0.91034798  0.2946781   0.38234726]]


In [30]:
# Slices 
c2 = np.arange(10,21)
print(c2)

# Fazendo o slice
print(c2[2:5])
print(c2[:5])
print(c2[2:])
print(c2[:])
print(c2[2:7:2])
print(c2[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
[12 13 14]
[10 11 12 13 14]
[12 13 14 15 16 17 18 19 20]
[10 11 12 13 14 15 16 17 18 19 20]
[12 14 16]
[18 17 16 15 14 13]


In [32]:
# Slice em array bidimencional
d2 = np.random.rand(5,5)
print(d2)
print('\n')

# primeiro é a linha, segunda posião é coluna e a terceira é o elemento
print(d2[0:2, 2])

[[0.0072489  0.07898371 0.36510338 0.38571169 0.80592393]
 [0.25316909 0.7891767  0.11570451 0.53694598 0.58710538]
 [0.85686477 0.34654026 0.33480362 0.46514014 0.32997581]
 [0.18628458 0.12130821 0.28285138 0.34614105 0.8805982 ]
 [0.43549983 0.09134849 0.08699427 0.48590605 0.37326053]]


[0.36510338 0.11570451]


# Operações com Arrays Numpy

In [38]:
# Com escalares
import numpy as np
a3 = np.ones(10)
print(a3)
a3 * 10
a3 / 2

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [41]:
b3 = np.random.randint(1,20,8)
print(b3)
b3 - 2
b3 ** 4

[ 8  8  2  9 18 17  4  2]


array([  4096,   4096,     16,   6561, 104976,  83521,    256,     16],
      dtype=int32)

In [47]:
c3 = np.random.randint(1,100,8)
print(c3)
b3 + c3
b3 - c3
b3 * c3
b3 / c3

[94 20 61 98  6 92 21 18]


array([0.08510638, 0.4       , 0.03278689, 0.09183673, 3.        ,
       0.18478261, 0.19047619, 0.11111111])

In [49]:
# Matriz 3 x 2
m1 = np.random.randint(1, 10, (3, 2))
print(m1)

[[8 3]
 [7 7]
 [3 8]]


In [50]:
m2 = np.random.randint(1,10,(2,3))
print(m2)

[[1 6 2]
 [3 5 9]]


In [53]:
# Multiplicação de matrizes
m1.dot(m2)

array([[17, 63, 43],
       [28, 77, 77],
       [27, 58, 78]])

In [ ]:
# Multiplicação de Array(matrizes)
m3 = np.ones((3,2))
m4 = np.ones((2,3))

print(m3)
print(m4)
m3.dot(m4)

# Comparações

In [57]:
s = np.array([1,2,2,1])
p = np.array([3,2,3,1])

#Comparando elemento por elemento dentro do array
s == p

#Comparando o array inteiro 
np.array_equal(s,p)

False

# Métodos de Funções Matemáticas

In [58]:
# Calculando ceno
np.sin(s)

array([0.84147098, 0.90929743, 0.90929743, 0.84147098])

In [61]:
# soma
np.sum(p)

9

In [63]:
# media 
np.mean(s)

1.5

In [65]:
# variancia
np.var(p)

0.6875

# Métodos Importantes e Máscaras em Arrays

In [67]:
array0 = np.random.randn(10)
array0

array([ 1.44355251,  0.07647714,  0.16564774,  0.43677244, -0.13553711,
       -1.08973634,  1.43723081, -1.48373251, -1.26630841, -0.97870541])

In [68]:
mtx = np.random.randn(3,3)
mtx

array([[-0.35411078,  1.32905232, -0.73841469],
       [ 0.66998563,  0.45394668, -0.26464296],
       [-1.68329019,  0.14290498,  0.28377198]])

In [70]:
# ndim retorna a dimensão de um array
array0.ndim
mtx.ndim

2

In [72]:
# shape retorna o formato
mtx.shape

(3, 3)

In [73]:
# dtype retorna o tipo do array
array0.dtype

dtype('float64')

In [75]:
# min retorna o valor minimo do array
array0.min()

-1.4837325068016292

In [76]:
# max retorna o valor maximo de um array 
array0.max()

1.443552508480389

In [ ]:
# argmin retorna a posição do menor elemento

In [77]:
array0.argmin()

7

In [78]:
# argmin retorna a posição do maior elemento
array0.argmax()

0

In [79]:
# sum - retorna a soma
array0.sum()

-1.3943391386045985

In [80]:
# mean - retorna a média
array0.mean()

-0.13943391386045983

In [82]:
# var - retorna a variancia
array0.var()

1.014787520132299

In [83]:
# std - desvio padrão 
array0.std()

1.0073666264733505

In [85]:
# sort - ordenação de array - ordena em ordem decrescente
array0.sort()
array0

array([-1.48373251, -1.26630841, -1.08973634, -0.97870541, -0.13553711,
        0.07647714,  0.16564774,  0.43677244,  1.43723081,  1.44355251])

In [86]:
# T - calcula a transposta
mtx.T

array([[-0.35411078,  0.66998563, -1.68329019],
       [ 1.32905232,  0.45394668,  0.14290498],
       [-0.73841469, -0.26464296,  0.28377198]])

# Máscaras

In [87]:
# Com mascaras é possivel selecionar os elementos que você quer enxergar
aa = np.array([1,2,3,4])
# Só vai me retornar as posições True
aa[[False, False, True, True]]

array([3, 4])

In [88]:
aa >= 3

array([False, False,  True,  True])

In [89]:
aa[aa >= 3]

array([3, 4])

In [90]:
aa[aa % 2 == 0]

array([2, 4])

In [91]:
aa % 2 == 0

array([False,  True, False,  True])