# NumPy Exercises
Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

Agora que aprendemos sobre o NumPy, vamos testar seus conhecimentos. Começaremos com algumas tarefas simples e então você será perguntado algumas perguntas mais complicadas.


# 1. Import NumPy as np

In [4]:
import numpy as np

# 2. Create an array of 10 zeros
Crie uma matriz de 10 zeros


In [5]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 3. Create an array of 10 ones
Crie uma matriz de 10 um


In [6]:
array1 = np.ones(10)
array1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 4. Create an array of 10 fives
Crie uma matriz de 10 cincos

In [7]:
array2 = np.array([5]*10)
array2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# 5. Create an array of the integers from 10 to 50
Crie uma matriz de inteiros de 10 a 50

In [8]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 6. Create an array of all the even integers from 10 to 50

In [9]:
arr2 = np.arange(10,51,2)
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 7. Create a 3x3 matrix with values ranging from 0 to 8
Crie uma matriz 3x3 com valores que variam de 0 a 8

In [10]:
mtx = np.array([[0,1,2], [3,4,5], [6,7,7]])
mtx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 7]])

# 8. Create a 3x3 identity matrix
Crie uma matriz de identidade 3x3

In [11]:
mt = np.eye(3,3)
mt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 9. Use NumPy to generate a random number between 0 and 1

 NOTE: Your result's value should be different from the one shown below.

Use NumPy para gerar um número aleatório entre 0 e 1

In [12]:
anr = np.random.rand(1)
anr

array([0.11063761])

# 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

  NOTE: Your result's values should be different from the ones shown below.
  
  Use NumPy para gerar uma matriz de 25 números aleatórios amostrados de uma distribuição normal padrão

In [13]:
ran = np.random.randn(25)
ran

array([ 1.43105207, -0.71672346, -0.91639115, -0.53211624, -0.01323684,
        0.67304601,  1.59922067, -0.02698178, -1.24180464,  0.18596424,
        0.60918682, -1.54865457, -0.16983088,  0.86971363, -0.84878601,
        2.47808373, -1.6423722 ,  0.22602949, -0.82231774,  0.46758116,
       -0.24414453,  0.36662096, -1.60094285, -0.08622251, -0.26218636])

# 11. Create the following matrix:
Crie a seguinte matriz:

In [16]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

# 12. Create an array of 20 linearly spaced points between 0 and 1:

In [17]:
lis = np.linspace(0,1,20)
lis

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection
Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 13. Write code that reproduces the output shown below.

  Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [21]:
mat[2:11,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

# 14. Write code that reproduces the output shown below.

In [22]:
arry = np.arange(20)
arry.shape

(20,)

# 15. Write code that reproduces the output shown below.

In [23]:
ary = np.array([[2],[7],[12]])
ary

array([[ 2],
       [ 7],
       [12]])

# 16. Write code that reproduces the output shown below.

In [24]:
ar = np.arange(21,26)
ar

array([21, 22, 23, 24, 25])

# 17. Write code that reproduces the output shown below.

In [25]:
arrb = np.array([[16,17,18,19,20], [21,22,23,24,25]])
arrb

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# NumPy Operations


# 18. Get the sum of all the values in mat

In [27]:
sun = np.arange(55,76,5)
np.sum(sun)

325

# 19. Get the standard deviation of the values in mat

In [28]:
des = np.arange(55,76,5)
np.std(des)

7.0710678118654755

# 20. Get the sum of all the columns in mat

In [29]:
a = np.arange(55, 76, 5)
print(a)
np.sum(a)

[55 60 65 70 75]


325

# Bonus Question
We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers?

Trabalhamos muito com dados aleatórios com numpy, mas há uma maneira de garantir que sempre tenhamos os mesmos números aleatórios?

In [35]:
np.random.seed(30)
np.random.rand(10)

array([0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781,
       0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ])

In [36]:
np.random.seed(30)
np.random.rand(10)

array([0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781,
       0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ])