# Criando Arrays

In [3]:
import numpy as np

In [6]:
# Crie uma matriz identidade com dimensão 5 x 5
array = np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# Crie uma matriz 3x3 com todos os elementos iguais a 1
array1 = np.ones((3,3))
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Crie uma matriz 2x3 com elementos de valores aleatórios entre 0 e 20
array2 = np.random.rand(2,3,20)
print(array2)

[[[0.56958724 0.33769504 0.20352817 0.59444565 0.69667658 0.09558206
   0.86328024 0.26857795 0.2780421  0.28693563 0.36381131 0.09584412
   0.42341328 0.34118925 0.58011723 0.08415614 0.15143833 0.11194917
   0.97566188 0.13391455]
  [0.520768   0.32448506 0.24810193 0.06943151 0.67020379 0.85145195
   0.91355193 0.37591981 0.60147737 0.7386006  0.78580915 0.9786456
   0.08428054 0.45080214 0.4103558  0.43129701 0.02443186 0.92880755
   0.49845073 0.72060787]
  [0.92072177 0.45108157 0.57531155 0.54261055 0.64083757 0.73636494
   0.24771156 0.98166573 0.67129179 0.17962015 0.81724303 0.21768678
   0.74530169 0.6665278  0.90933925 0.78396875 0.35557727 0.2321628
   0.12885075 0.88514324]]

 [[0.70215769 0.57051583 0.34413227 0.35620217 0.7440846  0.87549821
   0.32536734 0.92485059 0.29157368 0.45887652 0.62275641 0.4566004
   0.38531561 0.2233909  0.93723043 0.66712361 0.93638453 0.72120296
   0.25855722 0.17933497]
  [0.27239813 0.25143782 0.06101662 0.28125733 0.69729466 0.24520745


In [33]:
# Crie o vetor 
array3 = np.arange(9, 0, -1)
print(array3)

[9 8 7 6 5 4 3 2 1]
